language: java
jdk:
  - oraclejdk8
script:
  - gradle build
after_success:
 - curl --insecure --ssl-req -T ${projectRoot}/build/libs/${jarName} --url ftp://${user}:${password}@424v.cgodin.qc.ca
 - ssh ${user}@424v.cgodin.qc.ca
 - nohup java -jar webSocket-0.0.1-SNAPSHOT.jar > ./log.txt &
 - exit
