language: java
install: true
branches:
  except:
    - dev
jdk:
  - oraclejdk8
script:
  - cd ${projectRoot}
  - chmod +x ./gradlew
  - ./gradlew build --scan -s
addons:
  ssh_known_hosts:
  - 424v.cgodin.qc.ca
after_success:
 - cd $TRAVIS_BUILD_DIR
 - ssh ${user}@424v.cgodin.qc.ca "kill \$(lsof -t -i:8082)"
 - ssh "rm -f ${jarName}"
 - curl --insecure --ssl-req -T ${projectRoot}/build/libs/${jarName} --url ftp://${user}:${password}@424v.cgodin.qc.ca
 - ssh ${user}@424v.cgodin.qc.ca "nohup java -jar webSocket-0.0.1-SNAPSHOT.jar > ./log.txt &"
